import time
import os
from user_interaction import UserInteraction
from case import Case
from suspects import Suspects
from culprit import Culprit
from witnesses import Witnesses
from detective import Detective
from detective_attributes import DetectiveAttributes
from victim import Victim
#import notebook

# gets and stores all information of detective from save file for detective and assigns it to variables to be used in main.py
fame = DetectiveAttributes.fame
cases_solved = DetectiveAttributes.cases_solved

# stores the names of different save files into variables
case_data_file_path = 'case data.json'
case_file_file_path = 'case file.json'
detective_data_file_path = 'detective data.json'
suspects_info_file_path = 'suspects info.json'
suspect_report_file_path = 'suspects file.json'
witness_data_file_path = 'witness data.json'
witness_report_file_path = 'witness file.json'
culprit_data_file_path = 'culprit data.json'
victim_data_file_path = 'victim data.json'

suspect_generated = False

print("you have been transferred to the detective wing of the police department.")
print("")
print("--- enter any name other than the name of the previous detective's name to start a new account ---")

# asks the user for their detective name
detective_name = Detective.detective_name()
print('')

# The main flow of the game based on whether the save files exist
if os.path.exists(case_file_file_path) and os.path.exists(case_data_file_path) and os.path.exists(detective_data_file_path) and os.path.exists(suspects_info_file_path) and os.path.exists(suspect_report_file_path) and os.path.exists(witness_data_file_path) and os.path.exists(witness_report_file_path) and os.path.exists(culprit_data_file_path) and os.path.exists(victim_data_file_path):
    if detective_name == Detective.read_detective_info():
        print(f'Hello {detective_name}. Let\'s pick up your case right where you left it off.')
        print('')
        print(Case.read_case_file())
        print('')
        print('Opening investigator menu...')
        print('')
        time.sleep(2)

        print('The case is all yours, detective...')
        time.sleep(2)
        UserInteraction.commands()
        print('')

        while True:
            print('')
            user_menu_choice = input('Enter your choice here --> ')
            print('')
            if user_menu_choice == '1':
                UserInteraction.user_menu_interaction(user_menu_choice)
                break
            else:
                UserInteraction.user_menu_interaction(user_menu_choice)
                print('')
    else:
        fame = 0
        cases_solved = 0

        Detective.get_detective_info_as_dict(detective_name, fame, cases_solved)
        print('')

        print(f'Hello {detective_name}. I am Trevor, your in-charge. You seem new to this\nfield. Let\'s see what you\'ve got. You have a new case waiting for you.')
        print('')

        # Generates random case, and random case file according to information from the case
        Case.generate_case_and_case_file_random() # Generates random case, and random case file according to information from the case
        Suspects.generate_suspects_report_random() # Generates random information for all the suspects, based on the names generated by the case system
        Witnesses.generate_witness_and_witness_file_random() # Generates random information for the witnesses - names also generated from this function, based on the number of witnesses generted in the case system
        Culprit.set_culprit_details_final() # takes information from each of the attribute list in the suspects save file, regarding only the culprit, and saves it to another file
        Victim.generate_victim_data_random() # Generates random information for the victim - names are generated with the case, and not from within the victim class

        # Checks and validates the input
        while UserInteraction.question_start_solve() != '1':
            print('New Case:')
            Case.generate_case_and_case_file_random()
            Suspects.generate_suspects_report_random()
            Witnesses.generate_witness_and_witness_file_random()
            Culprit.set_culprit_details_final()
            Victim.generate_victim_data_random()

        # This is what happens if the user selects the given case instead of generating a new case
        print('Case selected')
        print('Opening investigator menu...')
        print('')
        time.sleep(2)

        print('The case is all yours, detective...')
        time.sleep(2)
        UserInteraction.commands()
        print('')

        while True:
            print('')
            user_menu_choice = input('Enter your choice here --> ')
            print('')
            if user_menu_choice == '1':
                UserInteraction.user_menu_interaction(user_menu_choice)
                break
            else:
                UserInteraction.user_menu_interaction(user_menu_choice)
                print('')
else:
    fame = 0
    cases_solved = 0

    Detective.get_detective_info_as_dict(detective_name, fame, cases_solved)
    print('')

    print(f'Hello {detective_name}. I am Trevor, your in-charge. You seem new to this\nfield. Let\'s see what you\'ve got. You have a new case waiting for you.')
    print('')

    Case.generate_case_and_case_file_random() # Generates random case, and random case file according to information from the case
    Suspects.generate_suspects_report_random() # Generates random information for all the suspects, based on the names generated by the case system
    Witnesses.generate_witness_and_witness_file_random() # Generates random information for the witnesses - names also generated from this function, based on the number of witnesses generted in the case system
    Culprit.set_culprit_details_final() # takes information from each of the attribute list in the suspects save file, regarding only the culprit, and saves it to another file
    Victim.generate_victim_data_random() # Generates random information for the victim - names are generated with the case, and not from within the victim class

    # Checks and validates the input
    while UserInteraction.question_start_solve() != '1':
        print('New Case:')
        Case.generate_case_and_case_file_random()
        Suspects.generate_suspects_report_random()
        Witnesses.generate_witness_and_witness_file_random()
        Culprit.set_culprit_details_final()
        Victim.generate_victim_data_random()

    # This is what happens if the user selects the given case instead of generating a new case
    print('Case selected')
    print('Opening investigator menu...')
    print('')
    time.sleep(2)

    print('The case is all yours, detective...')
    time.sleep(2)
    UserInteraction.commands()
    print('')

    while True:
        print('')
        user_menu_choice = input('Enter your choice here --> ')
        print('')
        if user_menu_choice == '1':
            UserInteraction.user_menu_interaction(user_menu_choice)
            break
        else:
            UserInteraction.user_menu_interaction(user_menu_choice)
            print('')